import {SelectedDiffOption, DiffListItem, DiffOptionObject} from './listResolveUtil';
export class MockDataService {

  public static getData(): any {
    return [
    new DiffListItem(0,
      new DiffOptionObject( "Age : Sensitivie", [
        
      ]),
      new DiffOptionObject( "Age : Aggregate", []),
      new DiffOptionObject( "Age : Sensitive", []),
      "Age", SelectedDiffOption.NotSelected),
    new DiffListItem(1, 
      new DiffOptionObject( "Date of Birth : No Access", []),
      new DiffOptionObject( "Date of Birth : Aggregate", []),
      new DiffOptionObject( "Date of Birth : No Access", []),
      "Date of Birth", SelectedDiffOption.NotSelected),
    new DiffListItem(2,      
      new DiffOptionObject( "First Name  : Sensitive", []),
      new DiffOptionObject( "First Name  : Aggregate", []),
      new DiffOptionObject( "First Name : Sensitive", []),
        "First Name", SelectedDiffOption.NotSelected),
    new DiffListItem(3,
      new DiffOptionObject( "Eye Color : No Access", []),
      new DiffOptionObject( "Eye Color : Aggregate", []),
      new DiffOptionObject( "Eye Color : Sensitive", []),
        "Eye Color", SelectedDiffOption.NotSelected),

    new DiffListItem(10,
      new DiffOptionObject( "Vacation Days : No Access",  []),
      new DiffOptionObject( "Vacation Days : Aggregate", []),
      new DiffOptionObject( "Vacation Days : No Access", []),
      "Vacation Days", SelectedDiffOption.NotSelected),
    new DiffListItem(4,
      new DiffOptionObject( "Hair Color : No Access",  []),
      new DiffOptionObject( "Hair Color : Aggregate", []),
      new DiffOptionObject( "Hair Color : No Access", []),
       "Hair Color", SelectedDiffOption.NotSelected),
    new DiffListItem(5,
      new DiffOptionObject( "Last Name  : Aggregate",  []),
      new DiffOptionObject( "Last Name  : Aggregate", []),
      new DiffOptionObject( "Last Name : Sensitive", []),
       "Last Name", SelectedDiffOption.NotSelected),
    new DiffListItem(6,
      new DiffOptionObject( "Height : Sensitive",  []),
      new DiffOptionObject( "Height : Aggregate", []),
      new DiffOptionObject( "Height : Sensitive", []),
           "Height", SelectedDiffOption.NotSelected),
    new DiffListItem(7,
      new DiffOptionObject( "Salary : No Access",  []),
      new DiffOptionObject( "Salary : Aggregate", []),
      new DiffOptionObject( "Salary : No Access", []),
        "Salary", SelectedDiffOption.NotSelected),
    new DiffListItem(8, 
      new DiffOptionObject( "Employee ID  : Sensitive",  []),
      new DiffOptionObject( "Employee ID  : Aggregate", []),
      new DiffOptionObject( "Employee ID : Sensitive", []),
       "Employee ID", SelectedDiffOption.NotSelected),
    new DiffListItem(9, 
      new DiffOptionObject( "Gender: No Access",  []),
      new DiffOptionObject( "Gender: Aggregate", []),
      new DiffOptionObject( "Gender : Sensitive", []),
       "Gender", SelectedDiffOption.NotSelected),
    new DiffListItem(11, 
      new DiffOptionObject( "Marital Status  : Aggregate",  []),
      new DiffOptionObject( "Marital Status  : Aggregate", []),
      new DiffOptionObject( "Marital Status : Sensitive", []),
       "Marital Status", SelectedDiffOption.NotSelected),
  ];
  }
}